# Generated by Django 4.2.8 on 2026-02-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_guide_faculty_id_project_guide_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('admin', 'Admin')], default='faculty', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
