# Generated by Django 6.0.1 on 2026-02-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_internship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internship',
            options={'ordering': ['-applied_date']},
        ),
        migrations.RenameField(
            model_name='internship',
            old_name='submitted_at',
            new_name='applied_date',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='position',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='status',
        ),
        migrations.AddField(
            model_name='internship',
            name='application_status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Selected', 'Selected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='internship',
            name='duration',
            field=models.CharField(default='3 Months', help_text='e.g. 6 Months', max_length=50),
        ),
        migrations.AddField(
            model_name='internship',
            name='faculty_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='internship',
            name='role',
            field=models.CharField(default='Intern', help_text='Job Role / Position', max_length=255),
        ),
        migrations.AddField(
            model_name='internship',
            name='skills_required',
            field=models.TextField(default='Python, Django', help_text='Comma separated skills'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='location',
            field=models.CharField(default='Remote', max_length=255),
        ),
        migrations.AlterField(
            model_name='internship',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
