# Generated by Django 4.2.8 on 2026-02-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='guide_faculty_id',
            field=models.CharField(default='', help_text='Faculty ID of the project guide', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='guide_name',
            field=models.CharField(default='', help_text='Name of the project guide faculty', max_length=255),
        ),
    ]
